# Generated by osspipeline. Do not edit.
# repo:     cli/cli
# source:   devcontainer
# evidence: .devcontainer/devcontainer.json
# evidence: .github/workflows/go.yml:build
# evidence: .github/workflows/go.yml
# evidence: leg matrix.os=ubuntu-latest of [ubuntu-latest windows-latest macos-latest]
# evidence: .github/workflows/lint.yml:lint
FROM mcr.microsoft.com/devcontainers/go:1.26
ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8 CI=1

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      make \
      pkg-config \
      unzip \
      xz-utils \
 && rm -rf /var/lib/apt/lists/*

ENV \
    GOCACHE=/cache/go/build \
    GOFLAGS=-mod=mod \
    GOMODCACHE=/cache/go/pkg/mod \
    GOPATH=/cache/go \
    GOTOOLCHAIN=auto

RUN if ! getent passwd 1000 >/dev/null 2>&1; then \
      getent group 1000 >/dev/null 2>&1 || groupadd -g 1000 ossp; \
      useradd -u 1000 -g 1000 -m -s /bin/bash ossp; \
    fi \
 && mkdir -p /cache/go \
 && chown -R 1000:1000 /cache/go \
 && mkdir -p /work && chown 1000:1000 /work

USER 1000:1000
WORKDIR /work
